### ISSUE TITLE
Log out from app

### ISSUE THREAD

**Issue by vekerdyb** [dangerfarms/fuqu-app#12]
As a User
I want to log out of the app
So that I can protect my privacy when I am not using the app

**Details**
There should be a log out button top right corner (in the header bar).
Clicking the logo will bring up a confirmation modal. If the user confirms the log out action the user is redirected to the login view.

The auth token that is stored locally should be removed.

Use a power icon from ionicons for the button.

The view should be accessible at `#/logout`.

**UI/Design**

For the modal, use Ionic's modal.
The button should be an `ion-power` icon.

**Tasks**

API

- none

Client

- [x] Create controller for the modal
- [x] Create (extend or use, if already exists) `User` service with `logout` method, that will remove the token
- [x] Create HTML / CSS Layout for the modal
- [x] Add logout button to menu

**Tests**  

Client
E2E
- [x] Should show modal on clicking the logout icon
- [x] Should hide modal when clicking cancel
- [x] Should hide modal when clicking logout in modal
- [x] Should redirect to login screen when clicking logout in modal

Unit
- [x] Should remove token from local storage when logout is confirmed

**Comment by vekerdyb** [comment]
Please add the button to either Profile or the Base view for now, so that we can test
