### ISSUE TITLE
View Leaderboard

### ISSUE THREAD

**Issue by vekerdyb** [dangerfarms/fuqu-app#13]
As a User
I want to view a Leaderboard of the best performing Queuers
So that I can see my rank amongst Queuers

**Details**
The leaderboard will show all users ordered by the number of queues reported the given week.

The frontend URL should be `#/profiles/leaderboard`.

The backend URL should be `/profiles/leaderboard/`

**UI/Design**

The design should be a list of custom items based on ionic ion-item directives.
Each item should display the user's rank, short username (the part preceeding @ in their email address), and the number of queues they reported.

**Tasks**

API

- [x] Create Resource URL `/profiles/leaderboar/`
- [x] Implement GET view

Client

- [x] Create LeaderboardListItem directive
- [x] Create LeaderboardList directive
- [x] Create Leaderboard module
- [x] Create Profile service (might have already been created)
- [x] Extend Profile service with .getLeaderboard() method, that makes the call to the backend
- [x] Create Controller using the Profile service
- [x] Create HTML/CSS layout
- [x] Set up routing 

**Acceptance Criteria**  

API

- [x] Should return unauthenticated if user is not logged in
- [x] Should calculate the number of queues since Monday midnight for each profile and include it in the response in the `queues` field
- [x] Should return an ordered list of profiles (descending order based on `queues`)

Client

E2E:
- [x] Should display the list of Users and their ranks
- [x] Should show error message if the requests return error

Unit: 
- [x] service should make `GET /profiles/leaderboard` request with on calling `Profile.getLeaderboard()`
- [x] controller should use the service to retrieve leaderboard data
- [x] controller should handle retrieval errors gracefully, setting error message variables

**Comment by vekerdyb** [comment]
@cfare: Great!
Please read the comments on commits.
Pay special attention to the test related comments.
Ask questions if something is unclear.
