### ISSUE TITLE
Profile information

### ISSUE THREAD

**Issue by vekerdyb** [dangerfarms/fuqu-app#14]
As a User
I want to see my basic Profile
So that I can confirm my data is correct

**Details**
The Profile will show basic profile information and stats.

The frontend URL should be `#/profiles/me`.

The backend URL should be `/profiles/me/`

**UI/Design**

The design should be a list of custom items based on ionic ion-item directives.
The item groups should be separated by ionic list dividers.
The first group should be called "Personal data" and should include the User's email address only. More groups will be added later.
The custom list items should display the name of the property (e.g.: 'Email', and the value e.g. 'test@test.com').

**Tasks**

API

- [x] Create Resource URL `/profiles/me/`
- [x] Implement GET view

Client

- [x] Create ProfileDetailListItem directive
- [x] Create ProfileDetailList directive
- [x] Create Profile module
- [x] Create (or extend) Profile service (might have already been created)
- [x] Extend Profile service with .me() method, that makes the call to the backend
- [x] Create ProfileDetail controller using the Profile service
- [x] Create HTML/CSS layout
- [x] Set up routing 

**Acceptance Criteria**  

API

- [x] Should return unauthenticated if user is not logged in
- [x] Should return the logged in user's Profile data

Client

E2E:
- [x] Should display the list of the Player's profile details
- [x] Should show error message if the requests returns error

Unit: 
- [x] service should make `GET /profiles/me` request with on calling `Profile.me()`
- [x] controller should use the service to retrieve Profile data
- [x] controller should handle retrieval errors gracefully, setting error message variables

**Comment by vekerdyb** [comment]
@lzmartinico: Good work!
Please see the comments on the commits.
One thing that I would highlight is the backend view, that can be simplified by using the built-in rest framework methods and classes.

**Comment by vekerdyb** [comment]
Well done! Will  close now.
For future reference, please have a look at https://github.com/dangerfarms/fuqu-app/commit/a209f18c294d8c6289958704ad2a68aa6825599e and ask if you have any questions about it.
