### ISSUE TITLE
Number of queues I submitted on Profile

### ISSUE THREAD

**Issue by vekerdyb** [dangerfarms/fuqu-app#15]
As a User
I want to see the number of Queues I submitted on my Profile
So that I can keep on eye on my progress

**Details**
The already existing Profile view needs to extended with the new information.

The number of queues can be calculated in the serializer as a method field. http://www.django-rest-framework.org/api-guide/fields/#serializermethodfield

The frontend URL is `#/profiles/me`.

The backend URL is `/profiles/me/`

**UI/Design**

No new design is required, just make it similar to the existing information.

Add a new group in the profile view, titled "Queues", and inside one item called "Submitted Queues".

**Tasks**

API

- [x] add `queues_submitted` method field in the profile serializer
- [x] implement the method that gets the number of queues for a given User 

Client

- [x] Add a ProfileDetailListItem with the information in the HTML/CSS layout

**Acceptance Criteria**  

API

- [x] Should return the number of Queues with the rest of the profile data

Client

E2E: (manual checking for now)  
- Should display the number of queues in the list of the Player's profile details
- Should display "-" (dash) if the number of queues is 0.

Unit: 
(none - no change in the logic is required)

**Comment by vekerdyb** [comment]
@BruceKey3: Good work! Nice to see you followed the TDD flow!
A couple of smaller issues is marked in the comments, please fix them, and the task is good to be closed.
