### ISSUE TITLE
Access views through a Side menu

### ISSUE THREAD

**Issue by vekerdyb** [dangerfarms/fuqu-app#19]
As a User
I want to access views through a Side menu
So I can navigate in a familiar way

**Details**
Look into http://ionicframework.com/docs/api/directive/ionSideMenus/

You will need to rework the base html files, as they are currently set to Tabs navigation.

Here is an example: 
https://github.com/driftyco/ionic-starter-sidemenu

Side menu should be on the left.

**UI/Design**
Keep it minimal, the default ionic design will probably do.

**Tasks**

API
none 

Client
- [x] restructure html files (index.html, base.html, etc.)
- [x] add menu items for Logout, Profile in an angular constant
- [x] create a Sidemenu controller that sets the menu items from the constant
- [x] remove Logout button from base.html

**Test**  
Client
E2E:
- [x] Side menu burger icon in header can be clicked to toggle the sidemenu on the left hand side
- [x] Animations still work with the side menu added
- [x] Clicking on side menu items takes you to the desired view

Unit: 
- [x] Controller should set the items from the constant

**Comment by vekerdyb** [comment]
@BruceKey3: Nice work!
For a few notes see the commit comments and the commits themselves.
