### ISSUE TITLE
Register for the app

### ISSUE THREAD

**Issue by lewistaylor** [dangerfarms/fuqu-app#2]
As a User
I want to register for the app
So that I can join this super-awesome queue-loving community

**Details**
The login page should contain a link to register where a User will be taken to a User registration page asking for the following fields:

* email address
* password (only once, people aren't idiots)
* submit button

**UI/Design**

Make use of the simple http://ionicframework.com/docs/components/#inset-forms component and other form inputs provided by ionic to create a simple form.

**Tasks**

API

- [x] Create Resource URL
- [x] Implement POST View
- [x] Add Signal to create Profile

Client

- [x] Create Register service 
- [x] Create Register controller to react to User actions
- [x] Create Register routing to let the app know where is everything available
- [x] Create HTML / CSS Layout
- [x] Create Register module to group behaviour into a single module (include all above as dependencies)
- [x] Include Register module to the main app module (`fuqu`) as a dependency

**Acceptance Criteria**  

API

- [x] Should return bad request if email not supplied
- [x] Should return bad request if password not supplied
- [x] Should return bad request if email already taken
- [x] Should create User given valid email/password and return created status
- [x] Should create an associated (blank) Profile on creation of the User

Client

E2E:
- [x] Should direct to registration view when clicking 'register' on login screen
- [x] Should redirect to home 

Unit: 
- [x] service should operate on a domain object (Restangular)
- [x] service should make POST /users/ request with the data passed in on calling .register(data)
- [x] controller should call service's .register() method on clicking register
- [x] controller should redirect to '/' if registration is successful (HTTP 2xx)
- [x] controller should set error message if registration is unsuccessful (HTTP 4xx)
