### ISSUE TITLE
View Queue data for a Place

### ISSUE THREAD

**Issue by vekerdyb** [dangerfarms/fuqu-app#22]
As a User
I want to view Queue data for a Place
So that I can make an informed decision about where to go when

**Details**

Two different pieces of information will be added in this task:
- Estimated queuing time
- Number of people currently queuing

For starters the Queue time estimation will be simply the average of queue times for the given place.

The data should be displayed in the PlaceListItem directive.

You will need to add a ListView for the Place object in the backend. 

URL: `GET /places/` filters on a list of place uuids

**UI/Design**

The PlaceListItem should already exist (#7) and should be extended with this data in a simple but visually pleasing way.

**Tasks**
API
- [ ] Create Place list view that returns the list of places and can be filtered by Place uuid

Client
- [ ] Use Places service's .getList method to retrieve the queue data in the Nearby Places and Place Search views (#7 and #21)

**Tests**
API
- [ ] should return list of queue items
- [ ] should return estimated queuing time for each place
- [ ] estimated queuing time should be average of all queuing times for that place
- [ ] should return number of people queueing for each place
- [ ] number of people queuing should be the number of unfinished queues for that place
- [ ] should filter on provided uuids 

Client
E2E:
- [ ] queue statistics should be displayed on the PlaceListItems
