### ISSUE TITLE
Login to the app

### ISSUE THREAD

**Issue by lewistaylor** [dangerfarms/fuqu-app#3]
As a User
I want to login to the app
So that I can start queueing like a maniac

**Details**
The login page should contain a button to login, which on clicking will bring up (in the same view) a login form allowing the user to login to the app. It should contain the following fields:

* email
* password
* submit button

The system should return a token for the User, using django-rest-framework's token authenticationwhich should be saved on the client for future requests. http://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication

**UI/Design**

Make use of the simple http://ionicframework.com/docs/components/#inset-forms component and other form inputs and buttons provided by ionic to create a simple form.

**Tasks**

API

- [x] Create Resource URL
- [x] Implement POST View

Client

- [x] Create HTML / CSS Layout
- [x] Create controller to react to User actions
- [x] Create service to communicate with API

**Tests**  

API

- [x] Should return token on successful login
- [x] Should return bad request if email not supplied
- [x] Should return bad request if password not supplied
- [x] Should return bad request if email not found
- [x] Should return bad request if credentials incorrect

Client

- [x] Should show login form on clicking on login button
- [x] Should not allow submission unless email and password filled
- [x] Should list error messages from API if bad request
- [x] Should store token in storage on successful response
- [x] Should redirect to home view on success

**Comment by vekerdyb** [comment]
@KOnaitis: Good work! 
Just a couple of small things, please see the comments on the commits.
(Pro Tip: go to https://github.com/dangerfarms/fuqu-app/issues/3 (or click on the detailed card title in waffle) to see commits related to the task, also see the text bubble icons to see which ones have comments)

**Comment by vekerdyb** [comment]
One more thing: initializing the login view should remove the token from local storage to avoid 403 when there is an invalid token stored locally. (But still handle unexpected errors gracefully)

**Comment by vekerdyb** [comment]
And one more: the 400 error response shows the error message "U" instead of "Unable to log in with provided credentials.". Probably a `[0]` in  the template.
